### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by AleTarsi**

### CODE REVIEW

**Comment by pattacini** [comment]
Hi @AleTarsi 

While opening `step_9`, I faced this problem:

```
=== Model Load (Elapsed: 0.70 sec) ===
    Warning:Workspace for block diagram 'step_9' was not loaded because an error occurred while loading the MAT-file 'C:\Users\atarsi\Desktop\InitialTutorial\Git_Pendulum\Pendulum\pendulum.mat'.
    Caused by:
        Cannot reload workspace from non-existing data source file 'C:\Users\atarsi\Desktop\InitialTutorial\Git_Pendulum\Pendulum\pendulum.mat'
```

It seems that you hand coded inside the model some absolute paths that clearly work only on your system.

Could you please sort it out and push a patch to this branch?

**Comment by pattacini** [comment]
By unplugging the PID as below, the system continues oscillating even with a super high damping factor.

image

Thus, there must be something wrong with the mechanical circuit below:

image

My suggestion is NOT to squeeze everything in one circuit only but to keep separate components: one for the damper and one for the actuation.

Tomorrow, I'll be away but @mfussi66 may give you support for debugging.

cc @nicogene

**Comment by AleTarsi** [comment]
> By unplugging the PID as below, the system continues oscillating even with a super high damping factor.
> 
> image
> Thus, there must be something wrong with the mechanical circuit below:
> 
> image
> My suggestion is NOT to squeeze everything in one circuit only but to keep separate components: one for the damper and one for the actuation.
> 
> Tomorrow, I'll be away but @mfussi66 may give you support for debugging.
> 
> cc @Nicogene

I believe I understood why disconnecting the PID we get a permanent motion on the Pendulum even though the dumper is set super high. I created a conflict in the following series of components: 

Starting from the working circuit below, tested and create by @pattacini in step8:

image

We have the velocity generator which create an angular velocity (across variable) from R to C pin which is dissipated through the dumper and results in a rotational torque (through variable). To keep thing clearer, at least to me, I will refer to Forces as Current and Angular velocity as Voltage.

Adding the torque source generator, as in the picture below, imposes a torque on the model which is not the one of the system, we impose 0 torque/current on that connection, which means zero dissipation, i.e. the rotational dumper does not dissipate energy and the pendulum oscillates continuously. 

image

Hence, what I did was to switch to the following model, in the picture below, which can be seen as an electric node, in which currents/torques sum. In this way we add to the system the torque generated by the PID controller. Changing the target value the wanted angular velocity is reached and disconnecting the PID brings the system back to a damped oscillating pendulum. Yet, there is the problem of unwanted oscillations, which I am currently analyzing.

image

The summing node:

image

**Comment by pattacini** [comment]
Hi @AleTarsi 

Well done! The circuit looks correct now 👍🏻 
However, this [issue](https://github.com/AleTarsi/Pendulum/pull/1#issuecomment-1711871506) still needs to be addressed.

Tomorrow after lunch, we can meet up and review together the model, including:
- Streamlining the Simscape blocks.
- Analysis of the control performance.

**Comment by AleTarsi** [comment]
> Hi @AleTarsi
> 
> Well done! The circuit looks correct now 👍🏻 However, this [issue](https://github.com/AleTarsi/Pendulum/pull/1#issuecomment-1711871506) still needs to be addressed.
> 
> Tomorrow after lunch, we can meet up and review together the model, including:
> 
> * Streamlining the Simscape blocks.
> * Analysis of the control performance.

Thank you @pattacini that would be of great help, as I didn't find a solution to the absolute path problem, neither I did find a robust solution.

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
You can safely merge it.

**Pull request merged**
